spring.application.name=Instagram Backend

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/instagram
spring.datasource.username=postgres
spring.datasource.password=nikO_151622

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1pbnN0YWdyYW0tYmFja2VuZA==
jwt.expiration=86400000

server.port=8080

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nurimuhammad7473@gmail.com
spring.mail.password=clxlcfpeyagaibxr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true